server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2000

  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true
mybatis:
  mapperLocations: classpath:mappers/*.xml
  configuration:
    mapUnderscoreToCamelCase: true


#spring:
#  application:
#    name: auto-c
#  datasource:
#    url: jdbc:mysql://10.248.61.27:3306/tms_test?useUnicode=true&characterEncoding=gbk&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: temp
#    password: Temp!2019
