server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2000

spring:
  application:
    name: auto-c
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=gbk&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true
mybatis:
  mapperLocations: classpath:mappers/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

#logging:
#  file: mylog1.log
#  level: info